---
name: LoveRate
main: FiePaw\LoveRate\Main
author: Fiepaw
version: 1.0
api:
- 4.6.0
commands:
  loverate:
    description: §c§lLove§6Rate§r mengetahui tingkat cinta
    permission: use.loverate
  love:
    description: §c§lLove§6Rate§r mengetahui tingkat cinta
    permission: use.loverate
permissions:
  use.loverate:
    default: true
...
